### ISSUE TITLE
Support for content property to change text

### ISSUE THREAD

**Issue by charliecm** [JohnCoates/CSSketch#12]
I think it would be useful if we can use the `content` property to update the content of a text layer. Even though this property is only valid in a `:before` element, I think in the context of Sketch, it can allow for more applications. For example, when creating a colour palette, we can define the name of the colour and its hex code, which will update the text layers in Sketch:

``` less
.color {
    .preview {
        background-color: #00ff00;
    }
    .name {
        content: 'Green';
    }
    .hex {
        content: '#00ff00';
    }
}
```

<img width="897" alt="preview" src="https://cloud.githubusercontent.com/assets/2857980/11255035/e5dfbbfc-8df8-11e5-9abf-5bf93b2bc1af.png">
